### ISSUE TITLE
Correct way of handling private_key through secrets

### ISSUE THREAD

**Issue by mikebell** [mrsixw/concourse-rsync-resource#11]
Hi,

I'm trying to figure out how to pass a private_key via concourse secrets.

I have the following pipeline:

```
---
resource_types:
- name: rsync-resource
  type: docker-image
  source:
      repository: mrsixw/concourse-rsync-resource
      tag: latest

resources:
- name: mikebell-io
  type: git
  source:
    branch: master
    uri: https://github.com/mikebell/mikebell.io.git
- name: sync-resource
  type: rsync-resource
  source:
    server: mikebell.io
    base_dir: /var/www/mikebell.io-test
    user : digital
    private_key: ${CONCOURSEPRIV}
    disable_version_path: true

jobs:
- name: Build
  public: true
  plan:
  - get: mikebell-io
    trigger: true
  - task: Build site
    config:
      platform: linux
      inputs:
      - name: mikebell-io
      outputs:
      - name: site
      image_resource:
        type: docker-image
        source: {repository: jekyll/builder}
      run:
        path: sh
        args:
        - -exc
        - |
          ls -lash
          chown jekyll:jekyll site
          jekyll build -s mikebell-io -d site
          echo ${CONCOURSEPRIV}
      params:
        CONCOURSEPRIV: ((concourse-priv))
  - put: sync-resource
    params: {
      CONCOURSEPRIV: ((concourse-priv)),
      "sync_dir": "site"
      }
# - name: Publish
#   plan:
#     put: sync-resource
```

The first echo works and prints the private key to the console however adding it to the params of the sync-resource results in:

> Load key "/root/.ssh/server_key": invalid format

If I replace the ${CONCOURSEPRIV} with the hardcoded key it works as expected.

Resources don't support params from what I can see so I can't add it directly to the resource.

I've tried adding the params to the resource type and no luck there.

Where is the right place to pass in the secret to the private_key?
