### ISSUE TITLE
Question: environment variables in base_dir?

### ISSUE THREAD

**Issue by airtonix** [mrsixw/concourse-rsync-resource#6]
was hoping to dynamically specify the `base_dir` with something like:

```yml
...
resources:
- name: artifacts
  type: rsync-resource
  source:
    server: {{artifacts_server}}
    base_dir: /data/$CONCOURSE_PIPELINE_ID/$CONCOURSE_BUILD_ID
    port: 2222
    user : root
    private_key: {{bitbucket_ci_private_key}}
...
```

Would this get evaulated by the `rsync-resource` container when it runs either of `check`, `in`, `out`?
